### ISSUE TITLE
Automatic Logging with Completion Handler Functions

### ISSUE THREAD

**Issue by Sherlouk** [kean/Pulse#10]
Hey there 👋 

I've been experimenting with Pulse in the context of a non-intrusive way of debugging our network calls. Specifically I'm looking at the [Automatic Logging](https://github.com/kean/Pulse/blob/0.9.1/Docs/Logging.md#21-automatic-logging) usage method.

The guide says "Use `URLSession` as usual." but I'm noticing that if I use the function below then the delegate functions don't get called and thus Pulse doesn't work.

```
func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
```

Is this expected? If so, perhaps some documentation tweaks would be useful!

I've also tried using the "Manual Integration" but I can't seem to find a nice way syntactically to capture the URLSession(Data)Task from within the completion handler to pass through to the NetworkLogger without storing a mutable task on the class.

Do you have a recommended pattern or is this the way you've been doing it?

Thanks 😄

**Comment by kean** [comment]
For completion-based API you can use the following approach:

```swift
let logger = Pulse.NetworkLogger(store: .default, blobStore: .default)
self.session = URLSession(configuration: .default, delegate: nil, delegateQueue: nil)

weak var dataTask: URLSessionDataTask?
dataTask = self.session.dataTask(with: URL(string: "https://github.com")!) { data, response, error in
    if let dataTask = dataTask {
        if let response = response {
            logger.logDataTask(dataTask, didReceive: response)
        }
        if let data = data {
            logger.logDataTask(dataTask, didReceive: data)
        }
        logger.logTask(dataTask, didCompleteWithError: error)
    }
}
dataTask?.resume()
```

Not ideal. You also won't be able to record metrics, so no nice charts. Delegate-based approach is preferred.

There are ways to automate this using `URLProtocol`. I have a functioning prototype, but haven't shipped it yet.

**Comment by Sherlouk** [comment]
Would definitely be interested in seeing your URLProtocol solution once it's ready! 😄  Thanks for sharing that snippet.

I have created an extension on the logger which makes it easy to send all three values at once for now to make it a little less intrusive.

**Comment by kean** [comment]
Added experimental `URLSessionProxy`, will be available in the upcoming build along with the documentation.

```swift
Experimental.URLSessionProxy.shared.isEnabled = true
```

There are *a lot of* limitations. `URLSessionProxyDelegate` is always preferred.

**Comment by kean** [comment]
You can now call `LoggerStore.default.storeRequest(request, response: response, error: error, data: data, metrics: nil)` to store the response directly. It's a single call, so it's much nicer.

The experimental URLProcotol-based logger is still in the same status. I don't know if anyone using is; I'm not.

I also completely rewrote the documentation. I hope it is now more clear https://kean.blog/pulse/guides/networking#automatic-logging.

If you are looking for fully automated solution, please give `Experimental.URLSessionProxy` a try and report any issues her e if you find them.
