### ISSUE TITLE
Build fails on Xcode 14 RC

### ISSUE THREAD

**Issue by collinhundley** [kean/Pulse#109]
In URLSessionProxyDelegate.swift, line 37 we get an error:

`Type 'any URLSessionTaskDelegate' has no member 'urlSession(_:didCreateTask:)'`

The method `urlSession(_:didCreateTask:)` doesn't seem to be available for some reason.

**Comment by kean** [comment]
Apparently, macOS 13.0 SDK was removed from Xcode in the RC.

**Comment by collinhundley** [comment]
@kean would it hurt to remove the `#if swift(>=5.7)` blocks until we get an Xcode version with the SDK back?

**Comment by kean** [comment]
Fixed in https://github.com/kean/Pulse/releases/tag/2.1.0
