### ISSUE TITLE
Build fails on Xcode 14 RC

### ISSUE THREAD

**Issue by OscarGorog** [kean/Pulse#110]
Getting this error when building on Xcode 14 RC:

- No such module 'Charts'
- Charts is not available when building for Mac Catalyst. Consider using `#if canImport(Charts)` to conditionally import this framework.

Seems to be related to #109

**Comment by kean** [comment]
My bad, I tested if `Pulse` compiles, but not `PulseUI`. Fixed in [2.1.2](https://github.com/kean/Pulse/releases/tag/2.1.2).

**Comment by OscarGorog** [comment]
Thank you!
