### ISSUE TITLE
Cocoa Pods

### ISSUE THREAD

**Issue by Vaberer** [kean/Pulse#111]
Why is not cocoa pods supported? The framework is great but without pods, it's not feasible.

**Comment by kean** [comment]
There are no plans to support CocoaPods. I recommend using XCFrameworks if SPM is not an option. Now that Xcode 14 is finally out, I'll start providing pre-built frameworks with every release.

**Comment by Vaberer** [comment]
That's not a good decision, we can use this library only via pods.

**Comment by Vaberer** [comment]
@leo150  let's ask @kean  to add this to this project. It's that easy.

**Comment by ZsoltMolnarMBH** [comment]
Hello @kean !

Our project is forced to used CocoaPods. It would be really nice if you could distribute Pulse over CocoaPods too.
Would you please consider?

**Comment by kean** [comment]
I'm planning to add CocoaPods support in 4.x.
