### ISSUE TITLE
Can't build project on Xcode 14.0.1

### ISSUE THREAD

**Issue by espinu** [kean/Pulse#115]
After adding the Pulse to the list of Packages the Xcode shows the error `Undefined symbols for architecture arm64:`

[Run-NyonOrder-2022.09.20_15-43-36-+0200.xcresult.zip](https://github.com/kean/Pulse/files/9608164/Run-NyonOrder-2022.09.20_15-43-36-%2B0200.xcresult.zip)

<img width="1208" alt="Screenshot 2022-09-20 at 15 45 13" src="https://user-images.githubusercontent.com/1833198/191274424-c59078aa-9fed-4b7d-a2fe-1330197d8d23.png">

**Comment by kean** [comment]
Can't repro. Most-likely project specific.

**Comment by kean** [comment]
Pulse uses Charts from Apple. I don't have any control of how it's imported. Not sure if there is anything I can do to address it from my end.

**Comment by arietis** [comment]
Yep, I agree. It's not a Pulse issue and should be resolved in the 3rd party Charts framework. https://github.com/danielgindi/Charts/issues/4917

**Comment by espinu** [comment]
@kean, @arietis  
How i hacked the solution:
I did the fork of the Pulse and changed the `Package.swift` to build as a dynamic instead of a static library and imported in the project only PulseUI. 

I assume something is wrong with the SwiftPackage manager 🤷‍♂️
