### ISSUE TITLE
Crash when filtering logs by Label or Function

### ISSUE THREAD

**Issue by AnthoPakPak** [kean/Pulse#116]
First, I want to thank you for this project, which can become really useful! I've integrated it and can't wait for it to save me some debugging time 😃

While trying it, I've noticed that both Pulse and Pulse Pro crash when trying to filter logs by either Label or Function. For example, on iOS, using Filter button > Changing "Message" to "Label" > Writing anything in the field > Crash. The same happens in Pulse Pro. And it also happens when filtering on Function.

Reported reason is `unimplemented SQL generation for predicate : (label CONTAINS[c] "typedText")`. I can provide the full crash log if needed.

You're probably already aware of this issue but I haven't seen this reported anywhere so I thought it might be a good idea to post an issue.

**Comment by kean** [comment]
Thanks for the report. Yes, the query seems is incorrect.

**Comment by kean** [comment]
Apparently, `function` is a reserved word and can't be used as a key.

**Comment by kean** [comment]
Fixed in [2.1.3](https://github.com/kean/Pulse/releases/tag/2.1.3)

**Comment by AnthoPakPak** [comment]
Just tried (both Pulse and Pulse Pro), all good! Thanks 👍
