### ISSUE TITLE
Installation guide points users to inaccessible PulseUI repo

### ISSUE THREAD

**Issue by nmccann** [kean/Pulse#12]
Hi, 

The installation guide located [here](https://kean.blog/pulse/guides/installation) asks users to add a package dependency with a URL of https://github.com/kean/PulseUI which requires access, now that the framework is available for free, should the documentation be updated to point to https://github.com/kean/Pulse?

PS. Thank you for your work on this project, and for providing it for free - I was looking to get all of my dependencies through SPM and this filled the last gap - network debugging, while providing the added benefit of supporting more general logging. The integration proved to be quite easy (even before `URLSessionProxyDelegate.enableAutomaticRegistration()`, it wasn't too difficult to get the proxy injected into AWS's Amplify framework, though it's even nicer with automatic registration).

**Comment by kean** [comment]
Thanks for reporting, @nmccann. I updated the guide.

https://github.com/kean/PulseUI was only needed when Pulse was only available for GitHub Sponsors.
