### ISSUE TITLE
Can't find PulseLogHandler package

### ISSUE THREAD

**Issue by deni2s** [kean/Pulse#123]
> As an alternative to using LoggerStore directly, you can use Pulse as a SwiftLog backend using [PersistentLogHandler](https://kean-docs.github.io/pulseloghandler/documentation/pulseloghandler/persistentloghandler) struct from [PulseLogHandler](https://kean-docs.github.io/pulseloghandler/documentation/pulseloghandler) which is a Swift package distributed separately. This way you can have more than one logger at once.

Where can I find the PulseLogHandler package which is distributed separately? There is no such module as well inside the Pulse package to include as per some docs...

**Comment by LePips** [comment]
Has `PulseLogHandler` been added to your project frameworks?

**Comment by deni2s** [comment]
Adding it under "Link binary with libraries" for each target did the trick, thanks, @LePips
