### ISSUE TITLE
Export copy create a bad file

### ISSUE THREAD

**Issue by mackoj** [kean/Pulse#13]
Hi @kean,

Thanks for building Pulse. I'm trying to using it I did follow your great documentation. But there is something that I'm not sure to completely understand.

When I do this an [export](https://kean.blog/pulse/guides/store#export) the file that has been exported cannot be opened by the macOS Pulse client. But when I go to the filesystem of the simulator in the /Library/Logs/com.github.kean.pulse/**current.pulse** this file actually is readable by the client.

Am I missing something ?

```swift
    let path = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    if var documentPath = path.first {
      let dateString = loggerDateFormatter.string(from: env.date())
      documentPath.appendPathComponent("\(dateString).pulse")
        let logInfo = try? LoggerStore.default.copy(to: documentPath)
        try? JSONEncoder()
          .encode(logInfo)
          .write(
            to: documentPath,
            options: Data.WritingOptions.atomicWrite
          )
    }
```

Thanks,

**Comment by kean** [comment]
Hey, `copy(to:)` creates a document at the given path. The returned value (`LoggerStoreInfo` – store metadata) is discardable and is not needed for most cases (I think I should remove it to make the API clearer). It looks like you are overwriting the actual document with `LoggerStoreInfo`.

**Comment by mackoj** [comment]
Yes I do, if I don’t write it myself the file is not created.

**Comment by mackoj** [comment]
My bad it's working

**Comment by kean** [comment]
"The destination directory must already exist." - that could be the cause.

**Comment by mackoj** [comment]
It was the default document user domain folder I think it might be because it was empty.
