### ISSUE TITLE
All documents are inaccessible

### ISSUE THREAD

**Issue by adad184** [kean/Pulse#132]
https://kean-docs.github.io/pulseui/documentation/pulseui/
https://kean-docs.github.io/pulse/documentation/pulse/

it's just empty right now, I checked the source code of the black page, it says

```
This page requires JavaScript. Please turn on JavaScript in your browser and refresh the page to view its content.
```

**Comment by Helloyunho** [comment]
It seems like the base url is wrong, guess I need to wait 'till Kean fixes it

**Comment by kean** [comment]
Thanks for the report, fixed!

Yes, it was the base URL. I need to simplify this.
