### ISSUE TITLE
[Question] What is the minimum required version for Pulse 3.0?

### ISSUE THREAD

**Issue by Helloyunho** [kean/Pulse#133]
I'd like to make my framework support as low versions as possible so I looked through README, but there's no mention of Pulse 3.0.

**Comment by kean** [comment]
Updated the README, thanks. It's the same as 2.0:

```
| Pulse 3.0  | Swift 5.6 | Xcode 13.3  | iOS 13.0, watchOS 7.0, tvOS 13.0, macOS 11.0  |
```

**Comment by kean** [comment]
Update: I am considering to increase the minimum deployment target to iOS 14 because there are a few things I just can't do properly in iOS 13.
