### ISSUE TITLE
Crash when using FirebaseAuth

### ISSUE THREAD

**Issue by anthonysoulier** [kean/Pulse#141]
Hello, 
When using `URLSessionProxyDelegate.enableAutomaticRegistration()` our app is crashing when Firebase tries to refresh the access token.
The crash is caused by an NSInvalidArgumentException exception

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GTMSessionFetcher setFetcher:forTask:]: unrecognized selector sent to instance 0x12e713340'
```

<img width="1259" alt="Screenshot 2023-01-18 at 11 29 12" src="https://user-images.githubusercontent.com/102587926/213161427-b8afb203-a32c-4e5b-aa3d-d77b0a6083e9.png">

<img width="1220" alt="Screenshot 2023-01-18 at 11 27 36" src="https://user-images.githubusercontent.com/102587926/213161420-51fa4dd1-df0b-4516-909b-50c188810d18.png">

**Comment by kean** [comment]
I'm not sure if there is anything I can do to fix that. I suggest either registering `URLSessionProxyDelegate` manual or using full manual logging. More info [here](https://kean-docs.github.io/pulse/documentation/pulse/networklogging-article).

**Comment by kean** [comment]
Addressed in https://github.com/kean/Pulse/issues/155

**Comment by anthonysoulier** [comment]
Thanks for addressing this, seems to be working now!
