### ISSUE TITLE
[Question] Empty URLSessionTaskDelegate

### ISSUE THREAD

**Issue by wow-such-amazing** [kean/Pulse#15]
Hi!

I really like the project and I'm giving it a try in one of mine projects. However I don't use URLSessionTaskDelegate and hence on my side I kinda don't need to provide a delegate to initialiser URLSession​Proxy​Delegate. Why URLSessionTaskDelegate is a non-optional parameter?

Thanks :)

**Comment by kean** [comment]
I re-wrote the documentation, so hopefully it is now more clear https://kean.blog/pulse/guides/networking#automatic-logging.

Without a delegate, there is no way to track any of the session events. If you are using the closure-based `URLSession`, I would suggest to either switch to a delegate, or log the requests manually like this:

```swift
LoggerStore.default.storeRequest(request, response: response, error: error, data: data, metrics: nil)
```
