### ISSUE TITLE
Every request is `Pending`

### ISSUE THREAD

**Issue by johndkouris** [kean/Pulse#153]
Like the title suggests, every request shows as `Pending` and never updates the status to either `Success` or `Failed`. The app is working fine, data is populating as it should.

Has anyone else had this problem? I'm running Pulse 3.2.1 on an iOS 16.0 sim

<img src=https://user-images.githubusercontent.com/105902212/215225051-a85d9e8f-ae3e-442e-9b63-dfab89974a04.png width=350>

**Comment by kean** [comment]
Potentially related: https://github.com/kean/Pulse/issues/113

**Comment by johndkouris** [comment]
Closing since #113 covers it
