### ISSUE TITLE
How can we do manual logging?

### ISSUE THREAD

**Issue by tahirmt** [kean/Pulse#156]
Is it possible to do manual logging that may or may not be a URLSessionTask? 

Pulse is pretty tightly integrated with the automatic logging. However if I want to use Pulse to manually add logs through my network stack instead of using the swizzling, there's very little information. Also, is it possible to decouple the logger from `URLSession` and `URLSessionDataTask` and instead take model objects that can easily be created from `URLSession` and `URLSessionDataTask` objects.

**Comment by kean** [comment]
You can also use [`LoggerStore/storeRequest`](https://kean-docs.github.io/pulse/documentation/pulse/loggerstore/storerequest(_:response:error:data:metrics:)) directly. It doesn't require `URLSession` and `URLSessionTask`.

**Comment by tahirmt** [comment]
@kean i wonder if there’s a way to show a custom header field value outside in PulseUI the list alongside the URL? Or just customize what gets shown in the list.

**Comment by kean** [comment]
No yet, but I have plans to add more settings.
