### ISSUE TITLE
Tapping on log entry doesn't open anything

### ISSUE THREAD

**Issue by deni2s** [kean/Pulse#158]
Noticed on 3.2.0 and 3.3.0 on iPad and iPhone.

Long press reveals some small window from where I can share details, but just tapping doesn't opens new view as it did before (to see request/response details).

**Comment by kean** [comment]
Hi, which iOS version are you using?

**Comment by deni2s** [comment]
Latest.

Seems it was my problem - I just replaced the deprecated MainView with ConsoleView and didn't noticed some other changes are required.
