### ISSUE TITLE
Why are PulseCore/PulseUI closed source ?

### ISSUE THREAD

**Issue by mackoj** [kean/Pulse#16]
Hi,

Why are PulseCore/PulseUI closed source ?

FWIW it is not possible to archive on Catalina because of these ;).

Thanks,

**Comment by kean** [comment]
It's closed-source because I want to keep my options open in terms of potentially releasing it as a proper product later. What most likely is going to happen, I will clean the code up and open source it.

> it is not possible to archive on Catalina because of these
Weird, is there a specific issue?

**Comment by mackoj** [comment]
> Weird, is it a known issue? Is there anything I can do to support it?

I will play around with it and tell you if I find a fix 😉

**Comment by kean** [comment]
I'm planning to open-source the whole thing so that folks who want to add features or debug it could do that.

**Comment by kean** [comment]
And it is now open-source starting with https://github.com/kean/Pulse/releases/tag/0.15.2
