### ISSUE TITLE
Some navigations don't work on iOS 14

### ISSUE THREAD

**Issue by AnthoPakPak** [kean/Pulse#166]
Hey,

I've just updated Pulse to the latest version (thanks for your work on it recently btw!).

I was using PulseUI in my UIKit app, by using `MainViewController`. Since it was behaving strangely after the update, I looked at the docs, and noticed `MainViewController` is now deprecated. According to the docs, showing `ConsoleView` in a `UIHostingController` should be sufficient to replace it. But by doing so, I only get the console view, nothing else.
By embedding `ConsoleView` in `NavigationView`, I get the top buttons with the menu allowing to access the other stuff (Insights, Settings…). Unfortunately, clicking those items don't do anything (except the Sponsor button).

I'm probably doing something wrong. Here's my code:

```
    static func showDebugUI(from vc: UIViewController) {
        let navView = NavigationView {
            ConsoleView()
                .navigationBarItems(leading: Button("Close") {
                })
        }
        
        let hostingController = UIHostingController(rootView: navView)
        let debugUIVC = hostingController
        vc.present(debugUIVC, animated: true)
    }
```

Could you please recommend the correct way to transition from `MainViewController` to `ConsoleView` with UIKit?

**Comment by kean** [comment]
Hi, I tested the provided code with the latest version of Pulse and it works well. Can you please provide a sample where I could reproduce it?

**Comment by AnthoPakPak** [comment]
Alright I have some findings. It was driving me crazy because it was working correctly on the test project I was making for you. But I was building my app on my iOS 14 iPhone, and the test project on the iOS 16 simulator. So here's the conclusion: opening those menus is broken on iOS 14. I've tried on iOS 15, works fine, so **only iOS 14 is affected**.
I can share with you the test project, but it is basically just the provided code above (tell me if you still want it).

**Comment by kean** [comment]
> I can share with you the test project, but it is basically just the provided code above (tell me if you still want it).

Thanks for providing the details. No, need for the project.
Yeah, it compiles on iOS 14, but there've been so many changes to how SwiftUI APIs work in iOS 15 that I barely support iOS 14. But I'll take a look. And PRs are always welcome as well.

**Comment by AnthoPakPak** [comment]
I would have loved to be able to help, but unfortunately I've looked at it, and being pretty novice with SwiftUI (trying to stay as far as possible from it), I'll probably won't be of any help. I would have started playing with the `.sheet()` or `NavigationView` handling in `ConsoleRouterView.swift`, but I don't know how navigation is supposed to be done in SwiftUI so I'd probably messed with something 😅

**Comment by kean** [comment]
Hey, I tried using the exact code you provided on iOS 14.5 (sim) and all navigations seems to work as expected:

```swift
 func showDebugUI(from vc: UIViewController) {
    let navView = NavigationView {
        ConsoleView()
            .navigationBarItems(leading: Button("Close") {
            })
    }

    let hostingController = UIHostingController(rootView: navView)
    let debugUIVC = hostingController
    vc.present(debugUIVC, animated: true)
}
```

Maybe there are some other conditions to reproduce it? Which specific iOS version have you tried?

**Comment by AnthoPakPak** [comment]
Hey! So I had tried on an iOS 14.3 physical iPhone and was able to reproduce it in a new project. I could try downloading other versions on the simulator to check if I can provide more information about the affected versions.

**Comment by kean** [comment]
I would appreciate it if you could look into it and make a fix. I'm not planning to invest more resources into iOS 14 support – I'm planning to remove it soon.

**Comment by kean** [comment]
The new version (Pulse 4.0) removes support for iOS 14. You can still integrate it in projects that target it, but the `ConsoleView` will show an error messages if it runs on a system below iOS 15. So I'm closing this ticket.
