### ISSUE TITLE
Is ZIPFoundation still a dependency?

### ISSUE THREAD

**Issue by lecniers** [kean/Pulse#17]
I added the package but I don't see ZIPFoundation as a dependency? 
Question: If any package is using ZIPFoundation, how is adding it to the project? I need to know because in my App I use ZIPFoundation as a dependency already so I'm testing Pulse in a temp project to evaluate it, I know Swift Packages with binaries can't depend on source packages.

**Comment by kean** [comment]
I have a stripped-down version of ZIPFoundation (~25% of features) included directly in my package. So yes, but you don't see it – it's private.

**Comment by lecniers** [comment]
I'm facing the same issues you described here: https://kean.blog/post/xcframeworks-caveats, I know this is not the place but Do you have any advice if I can't afford to strip down ZIPFoundation like you did and use it as a dependency of a binary swift package ? 

Thanks

**Comment by kean** [comment]
I basically just copy-pasted it and removed the stuff I didn't need to keep the framework lean. It's not a massive dependency anyway, so I think copying it fully should be fine. It's a Swift framework, so you won't see the type of name collisions during linking you would typically see in Objective-C frameworks.
