### ISSUE TITLE
Attempt to unwrap a non-optional value

### ISSUE THREAD

**Issue by serikabdirov** [kean/Pulse#178]
Xcode 14.3, Swift 5.8

File: NetworkInspectorSummaryView.swift

Attempt to unwrap a non-optional value

`            if let responesHeaders = viewModel.responseHeaders {
                NavigationLink.programmatic(isActive: $viewModel.isResponseHeadearsRawLinkActive) {
                    NetworkHeadersDetailsView(viewModel: responesHeaders)
                }
            }
`

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/76536660/229047738-b19928ca-ea2c-4d5b-a1d9-d5658d2110a8.png">

**Comment by MoElnaggar14** [comment]
Did you fix it? @serikabdirov

**Comment by serikabdirov** [comment]
Yes, I had to update framework to current version 👌

**Comment by MoElnaggar14** [comment]
Thanks 🙏🏻
