### ISSUE TITLE
PulseUI not honouring NetworkFlag

### ISSUE THREAD

**Issue by chetan-kmr-0607** [kean/Pulse#179]
Hi Team,
Recent version is not supporting network filtering under ConsoleView

**Code:**
`ConsoleView.network()`

**O
![Simulator Screenshot - iPhone 14 - 2023-04-03 at 08 37 44](https://user-images.githubusercontent.com/118420797/229412778-9fb5fbdd-00d2-45e1-8c5e-d101ea3f3138.png)
utPut:**
![Simulator Screenshot - iPhone 14 - 2023-04-03 at 08 37 48](https://user-images.githubusercontent.com/118420797/229412789-6cb6bc18-1a30-43aa-974a-77018a6959f7.png)

**Comment by kean** [comment]
Fixed in [3.5.6](https://github.com/kean/Pulse/releases/tag/3.5.6)
