### ISSUE TITLE
Crash using Swizzled Automated Logging and Firebase Remote Config

### ISSUE THREAD

**Issue by AgapovOne** [kean/Pulse#18]
Hello. I know the framework is closed-source so I can't dig deeper and debug why exactly that crash happened.

On my work project I use Firebase Remote Config instantiated with default `RemoteConfig.remoteConfig()` (like in [docs](https://firebase.google.com/docs/remote-config/get-started?authuser=0)).

That's a step after enabling swizzled Automated Logging.

The crash is a simple EXC_BAD_ACCESS:

I can make it working with manual logging, of course, but I do swizzling to log requests inside modules.

I can setup basic project to test that crash, but it would require Google-Info.plist from firebase.

The unsymbolicated part is two calls from PulseCore:
```
0   libswiftCore.dylib            	0x0000000190bf9110 swift_getObjectType + 40
1   PulseCore                     	0x00000001067b9bec 0x106784000 + 220140
2   PulseCore                     	0x00000001067b9bec 0x106784000 + 220140
```

And two pictures of what's going on inside Firebase at steps before PulseCore:
![CleanShot 2021-06-11 at 14 25 36](https://user-images.githubusercontent.com/4246455/121664525-023d4200-cac1-11eb-88d5-981a6c2becd7.png)
![CleanShot 2021-06-11 at 14 26 00](https://user-images.githubusercontent.com/4246455/121664535-04070580-cac1-11eb-8138-b693b26d768c.png)

I'll try to setup a little project a bit later.

**Comment by kean** [comment]
Thanks. I'm going to open-source the part that's performing the logging some time later today. Not entirely sure why it's crashing. The safest option is to log manually.

**Comment by kean** [comment]
I'm taking a one week break, and I'm planning to open-source the whole thing so that folks who want to add features or debug it could do that.

**Comment by AgapovOne** [comment]
I've tried to use automatic network logging again with current versions.
Not all requests were logged now, so I changed to Alamofire event monitor based logging. Also, I didn't get any crash now.

Closing an issue.
