### ISSUE TITLE
Crash while swiping a cell to share

### ISSUE THREAD

**Issue by hugovanderlei** [kean/Pulse#180]
Pulse is crashing when a cell is swiped to share something.

This is where it crashes:

<img width="1432" alt="Captura de Tela 2023-04-07 às 09 40 39" src="https://user-images.githubusercontent.com/184836/230610527-5437e4c9-2856-4025-a676-96aeb38a600e.png">

**Comment by kean** [comment]
Thanks for the report. I also found it today and fixed it in the [pulse-macos](https://github.com/kean/Pulse/pull/177) branch in case you need a quick fix.

**Comment by kean** [comment]
Fixed in [3.5.7](https://github.com/kean/Pulse/releases/tag/3.5.7)
