### ISSUE TITLE
Pulse fails to build in Xcode 14.3

### ISSUE THREAD

**Issue by dotswift** [kean/Pulse#181]
## NetworkInspectorSummaryView
- Error reads `Initializer for conditional binding must have Optional type, not 'KeyValueSectionViewModel'` 

### Screenshot 
<img width="1050" alt="Screenshot 2023-04-10 at 3 14 09 PM" src="https://user-images.githubusercontent.com/45957246/230978896-3ad53051-9e24-45c3-bdc6-5e0802a64230.png">

**Comment by kean** [comment]
Hey, which version are you using?

**Comment by JeanAzzopardi** [comment]
I am getting the same issue in 3.5.1

**Comment by lerolli** [comment]
Same problem. Using Pulse 2.1.4

**Comment by kean** [comment]
Fix in version [2.1.5](https://github.com/kean/Pulse/releases/tag/2.1.5). I recommend switching to Pulse 3.x. It does require iOS 14, which I'm going to guess prevents some teams from upgrading.
