### ISSUE TITLE
Pulse SwiftUI missing Devices sidebar

### ISSUE THREAD

**Issue by dnKaratzas** [kean/Pulse#182]
Hello! 
It would be nice to implement the `Devices` sidebar on the new Pulse mac app like on `Pulse Pro`.
It is really help-full to fast switch devices.

`Pulse Pro`
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/7944881/231445516-5bf875aa-edab-41e8-adf5-8a75c683bcb8.png">

**Comment by kean** [comment]
Hey, thanks for taking the new version for a spin. The devices inspector is already implemented, with a few major improvements compared to the Pulse Pro version. For example, working with [multiple apps](https://github.com/kean/PulsePro/issues/15) with Pulse on the same device is now easier. The release is coming sometime soon (1-2 months).

<img width="701" alt="Screenshot 2023-04-12 at 8 29 24 AM" src="https://user-images.githubusercontent.com/1567433/231457166-465d1fc6-2e2e-49c8-9289-2d1f985bbce5.png">

**Comment by dnKaratzas** [comment]
@kean  nice to hear that. 
So the https://github.com/kean/Pulse/releases/tag/3.6.0-alpha.2 is not contain that as I get it right?

**Comment by kean** [comment]
Yes, and there will be at least three new inspectors in the release version.

Errors and warnings:

<img width="596" alt="Screenshot 2023-04-12 at 8 35 00 AM" src="https://user-images.githubusercontent.com/1567433/231458797-16472835-8249-4052-8550-6af799754a59.png">

Sessions:

<img width="613" alt="Screenshot 2023-04-12 at 8 35 07 AM" src="https://user-images.githubusercontent.com/1567433/231458812-6ba29807-ca66-4d9e-ae9a-fda2d8d97923.png">

Sessions are also coming to iOS in Pulse 3.6, which will be released sooner than Pulse for Mac.
