### ISSUE TITLE
Two "Close" buttons in Console

### ISSUE THREAD

**Issue by OneSman7** [kean/Pulse#183]
I just updated to the recent version (3.5.4 -> 3.5.7) and see this in Console))
I think screenshot says it all :D 
It does not prevent from using console - both buttons work.

![photo_2023-04-13 19 08 33](https://user-images.githubusercontent.com/4619076/231820614-088d8f5f-bb36-4f0d-b08f-0c75777d7479.jpeg)

**Comment by kean** [comment]
Hey, can you the code that shows the console please?

**Comment by OneSman7** [comment]
```
func presentPulseLogging(on controller: UIViewController) {
        
        let vc = PulseUI.MainViewController(store: .shared) { [weak controller] in
            controller?.dismiss(animated: true, completion: nil)
        }
        
        vc.modalPresentationStyle = .fullScreen
        
        controller.present(vc, animated: true, completion: nil)
    }
```

**Comment by OneSman7** [comment]
It seems 2 buttons come from here

<img width="848" alt="Снимок экрана 2023-04-13 в 21 11 47" src="https://user-images.githubusercontent.com/4619076/231847366-b930874e-6188-4d03-ad08-9c844cec9b8f.png">

**Comment by OneSman7** [comment]
It was needed previously to provide `onDismiss` to close console correctly. Seems now it is not necessary and results in 2 buttons :)

**Comment by kean** [comment]
Yes, you can remove `onDismiss` for now as a workaround. I'm going to update the API in the upcoming release to fix it.

**Comment by kean** [comment]
Fixed in [3.6.0](https://github.com/kean/Pulse/releases/tag/3.6.0).

**Comment by OneSman7** [comment]
Hello again!
Now on iOS 14 no close button is displayed. Will have to resort to display console not fullscreen to be able to close it. Maybe it is connected to @Environment(\.presentationMode) being debrecated, but I am not sure.

**Comment by kean** [comment]
I don't know; this API has been hit or miss. In my testing, it works, but it depends on how you present it and what View/ViewController hierarchy.

The expected behavior is that it should be displayed by default. I would appreciate it if you could provide a sample where I can reproduce it.
