### ISSUE TITLE
[Pulse 4] App crashes if it's not updated to version 4

### ISSUE THREAD

**Issue by hugovanderlei** [kean/Pulse#190]
I've been testing the Pulse 4, it's wonderful, thank you very much!

I tested it by updating to the new version, had some issues connecting, but it worked out. However, if I use an app that is not updated to version 4, and the new Pulse mac app is opened, the app crashes. The Pulse's version used was 3.7.1.

![Captura de Tela 2023-05-10 às 09 51 18](https://github.com/kean/Pulse/assets/184836/3cb843b1-7bca-4d5b-8ae8-7f294835d12f)

**Comment by kean** [comment]
It should be fixed in version 4.0.0 (3) that I just pushed to TestFlight this morning.

Duplicate: https://github.com/kean/Pulse/issues/188
