### ISSUE TITLE
Crash when pushing ConsoleView PulseUI Logger on Device only

### ISSUE THREAD

**Issue by jgodonQobuz** [kean/Pulse#193]
Hi Kean 👋 

# Crash

I have a crash from Pulse version 3.6.0 (also present on 4.0-beta) but not in 3.5.7 version that works well. More over this crash only appears on device and not on Simulator.

The app crashes when pushing `ConsoleView(store: loggerStore)` via a `NavigationLink`.
It's in class `RemoteLogger` / `func cancelConnection` on the precondition 

```
public final class RemoteLogger: RemoteLoggerConnectionDelegate {
...
    private func cancelConnection() {
        precondition(DispatchQueue.getSpecific(key: specificKey) != nil)
...
    }
```

# Logs
For the moment, Xcode does not want to give me any crashlogs but I'll try again later

I'm running iOS 16.4.1 (a) on iPhone 13 mini

Here are 2 screenshots :

![Capture d’écran 2023-05-11 à 15 30 42](https://github.com/kean/Pulse/assets/114389226/628ec469-8394-49c1-8bec-848b9c2a59d3)

![Capture d’écran 2023-05-11 à 16 39 54](https://github.com/kean/Pulse/assets/114389226/69439f47-a77b-40d8-88fd-9d8c65ebf800)

Hope it can helps...

Cheers

Jeremie

**Comment by kean** [comment]
Fixed in version [3.7.2](https://github.com/kean/Pulse/releases/tag/3.7.2).
I'm considering making it an Actor in version 4.0.
