### ISSUE TITLE
[Feature] Ability to share/export network log as Raw HTTP Messages

### ISSUE THREAD

**Issue by SVMichael** [kean/Pulse#195]
This is useful for importing the same file coming from pulse to other proxy programs such as [Proxyman ](https://proxyman.io/)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

**Comment by kean** [comment]
It's in the backlog, but I haven't yet found any library to generate the HAR archives. I'm planning to add support for importing/exporting HAR archives.
