### ISSUE TITLE
Ability to export logs programatically

### ISSUE THREAD

**Issue by jostster** [kean/Pulse#203]
It would be a nice to have to allow the developer to create a button that says export logs that a user can tap and we export the logs  with defined settings instead of giving the user access to the UI so they can export the logs. This helps make submitting logs with bug reports much simpler.

**Comment by kean** [comment]
Hey, have you tried using the new `LoggerStore/export` API from version [3.6.0](https://github.com/kean/Pulse/releases/tag/3.6.0)?

**Comment by jostster** [comment]
> Hey, have you tried using the new `LoggerStore/export` API from version [3.6.0](https://github.com/kean/Pulse/releases/tag/3.6.0)?

I looked at the documentation for LoggerStore but didn't see an `export`. I will be sure to check again. Thank you!

**Comment by kean** [comment]
The docs have been updated: https://kean-docs.github.io/pulse/documentation/pulse/loggerstore/export(to:as:options:)
