### ISSUE TITLE
Pulse overrides the app's accent color

### ISSUE THREAD

**Issue by MrAsterisco** [kean/Pulse#207]
Hello!

I am embedding Pulse into my SwiftUI application via Swift Package Manager. Updating to any version higher than `3.5.7` causes the app accent color to be overridden to the default blue, regardless of what I have set in my Assets catalogue.

I tried to change the `Global Accent Color Name` build setting in my app target to another name (not the default `AccentColor` that I was using before) but nothing changes: it seems that Pulse is somehow overriding my color.

With version `3.5.7` everything works normally.

Is this a known issue? How can I work around it? I tried looking for similar issues on the repo but couldn't find any: is this a problem with only SwiftUI apps?

**Comment by kean** [comment]
Hey, @MrAsterisco. Pulse doesn't make any app-level changes and never accessed the view hierarchy outside of its views, so it seems unlikely it would have such an effect. Can you please provide a sample that reproduces it?

**Comment by kean** [comment]
Potentially related: in Pulse 4.0.2, the Console view now respects the app's accent color for all its controls.

**Comment by MrAsterisco** [comment]
Hey sorry for not updating the issue: I was taking some time off. After my initial investigation, it seems that, as you said, the problem is caused by my project configuration. Although, it is caused by Pulse, I was not able to reproduce it in a new SwiftUI project.

To recap what I'm seeing:
- Updating to any version of Pulse higher than 3.5.7 causes the app to lose the accent color that I set and use the blue accent color that is defined in the Pulse project (not only in the Pulse UI, but also everywhere else in the app).
- However, this only happens in my project (which unfortunately is closed-source, so I cannot share it) and it does not happen in a new project.

Thank you anyway for your help.
I will try to update to 4.0.2 to see if that fixes the issue, otherwise I'll have to continue investigating where the conflict happens.

**Comment by MrAsterisco** [comment]
Yes, I looked into it weeks ago, but still couldn't find a reason. It is definitely that, but I don't know why it would be included: I am using SPM.

**Comment by MrAsterisco** [comment]
To add even more context, invoking `LoggerStore.shared` while the app is starting (which I do because I'm appending content to the Pulse log manually through my logging infrastructure, which gets instantiated on app start) triggers the issue.

Delaying the first log to the time the first window is visible **does not** trigger the issue.

**Comment by MrAsterisco** [comment]
The same also happens when instantiating the `NetworkLogger`. So it seems Pulse is doing something _statically_ regardless of which class is instantiated?

**Comment by kean** [comment]
I wish I could help as I understand it seems pretty frustrating, but there is absolutely nothing that the framework does on the global label and includes no resources. 

There is an appearance override in https://github.com/kean/Pulse/blob/32707c62d9ee9ca5f0aefd090781cb0b384c8d62/Sources/PulseUI/Views/PulseUI%2BUIKit.swift#L46, but it's localized to `MainViewController` and this code doesn't run until you show it. If you are using SwiftUI, it never runs.

**Comment by MrAsterisco** [comment]
Well... I solved it! Maybe I was doing something wrong on my side and, for whatever reason, Pulse was highlighting my wrong doing... no idea.

In any case, I was instantiating `NetworkLogger` and `LoggerStore` as properties of the `App` instance (indirectly through injected dependencies). Moving them to the main view of the app solved the issue!

The key point was debugging when the `NetworkLogger` was being initialized: before it was happening in the `init` function of the `App` struct, which apparently it's not a good place to initialize Pulse.
