### ISSUE TITLE
"NSObject.deinitKey" in objc_setAssociatedObject raises warning 

### ISSUE THREAD

**Issue by egesucu** [kean/Pulse#209]
Following warning appears on the new Xcode 15 beta:

"Forming 'UnsafeRawPointer' to an inout variable of type String exposes the internal representation rather than the string contents."

Additional Info:

* Pulse SDK version 3.7.3
* macOS Sonoma 14.0 Beta (23A5301g)

**Comment by egesucu** [comment]
<img width="1117" alt="image" src="https://github.com/kean/Pulse/assets/16636371/9944c89e-244b-4c47-9b4e-f311a0615dba">

**Comment by kean** [comment]
Thanks for the report! It's fixed in version 4.0. I would recommend giving the latest beta a try. It's pretty close to the release and there aren't any significant breaking changes.

**Comment by egesucu** [comment]
> Thanks for the report! It's fixed in version 4.0. I would recommend giving the latest beta a try. It's pretty close to the release and there aren't any significant breaking changes.

I can confirm that this is fixed on the latest 4.0 beta
