### ISSUE TITLE
ConsoleView iOS 14 support

### ISSUE THREAD

**Issue by OneSman7** [kean/Pulse#213]
Although Pulse 4 supports iOS 14 on paper, it is almost useless since ConsoleView does not support it. Is there any way to bring back its functionality to this iOS version? Maybe it is possible to limit some functionality (even radically), but bring it back. Core feature needed is the ability to view network logs on the device.

**Comment by kean** [comment]
Version 4 uses a lot of APIs introduced in iOS 15. I doubt it's feasible to bring back the iOS 14 support. My main concern isn't necessarily the new features but the changes in the behavior of the existing APIs I noticed after upgrading. If someone decided to tackle it and open a PR, I would merge and release it, but I don't have the resources to make these changes myself.
