### ISSUE TITLE
Update podspec to include other platforms

### ISSUE THREAD

**Issue by scornflake** [kean/Pulse#215]
Unsure if the current podspec is complete or not, but trying to add to a mac app I get:

```
(macOS 13.00) is not compatible with `PulseCore (4.0.2)`, which does not support `macOS`.
```

guessing the various platforms as supported in Package.swift need adding to the podspec.

**Comment by kean** [comment]
The podspec supports only iOS. I've been running into too many issues with CocoaPods on other platforms, so I'm not considering adding support for the other platforms.
