### ISSUE TITLE
All requests is pending with async await

### ISSUE THREAD

**Issue by vitys96** [kean/Pulse#222]
Hi! I use common try await session.data(for: request) for network requests. 
How I can connect pulse with async/await? 
Should I manually add pulse logger to my network service?
<img width="983" alt="image" src="https://github.com/kean/Pulse/assets/36761441/d25884d3-8812-46e8-ba47-9f69fd70609e">

**Comment by kean** [comment]
Closing as duplicate of https://github.com/kean/Pulse/issues/113
