### ISSUE TITLE
Cant find settings view of the iOS plugin

### ISSUE THREAD

**Issue by ahmadmssm** [kean/Pulse#225]
Hi,

I'm facing two issues with the recent versions of PulseUI.
1. I can't reach the settings page of the iOS App plugin mentioned [here](https://kean-docs.github.io/pulse/documentation/pulse/gettingstarted/#42-Enable-Remote-Logging).
2. I can't go into the details of the API requests in the network view.

Other than that it looks neat.

**Comment by kean** [comment]
Hey, can you please share the code that you use to present the console?

**Comment by ahmadmssm** [comment]
```
.sheet(isPresented: self.$showHttpLogger) {
      ConsoleView()
}
```

**Comment by kean** [comment]
It needs to be wrapped in a navigation view:

```swift
        .sheet(item: $presentedStore) { store in
            NavigationView {
                ConsoleView(store: store)
            }
```

It's not wrapped in one by default to allow users to integrate it in their existing view hierarchies.

**Comment by ahmadmssm** [comment]
Got it, thank you.

**Comment by ahmadmssm** [comment]
By the way, there are some links in the docs that need to be updated in general.

**Comment by kean** [comment]
I would appreciate if you could point out which ones, or, even better open a PR with an update.

**Comment by ahmadmssm** [comment]
Will do shortly.
