### ISSUE TITLE
Missing 4.0.5 in pod trunk

### ISSUE THREAD

**Issue by AgapovOne** [kean/Pulse#234]
Hello. Tried to update pods in my local app, but didn't find last version in trunk.

```
pod trunk info PulseUI

PulseUI
    - Versions:
      - 3.7.3 (2023-06-06 03:21:30 UTC)
      - 4.0.0 (2023-08-06 19:20:02 UTC)
      - 4.0.1 (2023-08-07 21:25:58 UTC)
      - 4.0.2 (2023-08-20 00:43:25 UTC)
      - 4.0.3 (2023-08-28 01:21:10 UTC)
    - Owners:
      - kean <grebenyuk.alexander@gmail.com>
```

How can I help with that and publish 4.0.4, 4.0.5? Is there a script that didn't run for 4.0.4 and 4.0.5?

**Comment by AgapovOne** [comment]
4.0.5 is there now, thanks

**Comment by kean** [comment]
Hey, thanks for the reminder. I pushed an update.
I've been avoiding automating this part of the flow because it feels like every time I try to push a spec, there is a new issue that I have to deal with.
