### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by cpd** [kean/Pulse#246]
Pulse 4.0.5

Creating a proxy delegate (`let delegate = URLSessionProxyDelegate()`) leads to deadlock because of Coredata `performBlockAndWait`

<img width="368" alt="image" src="https://github.com/kean/Pulse/assets/26257647/ca975e9a-e062-4e6e-b714-d0ce7a944756">

TCA on main thread
<img width="1116" alt="image" src="https://github.com/kean/Pulse/assets/26257647/e8bc6f64-4d43-4fe3-96b4-b1e23f0e7240">

Pulse
<img width="1188" alt="image" src="https://github.com/kean/Pulse/assets/26257647/5b97ce85-effe-4572-923e-34b20594af7c">

after wrapping these in an async block 
<img width="688" alt="image" src="https://github.com/kean/Pulse/assets/26257647/8c242f7c-b069-457c-83fe-1ff380e841f5">

the app is stuck in `LoggerStore.postInitialization()`
<img width="1266" alt="image" src="https://github.com/kean/Pulse/assets/26257647/ca08da26-8bcb-4572-9dfb-2a6283a7ffa9">

using async version fixes problem but since I have zero experience with core data this is probably wrong solution
<img width="887" alt="image" src="https://github.com/kean/Pulse/assets/26257647/106fca34-c456-45fb-b973-ab1b8b62d1f3">

**Comment by kean** [comment]
Thanks for the detailed report, @cpd. It should be fixed in https://github.com/kean/Pulse/releases/tag/4.1.1.
**Workaround**: make sure the store is initialized somewhere in your app delegate before you record any logs – simply access `LoggerStore.shared` to get it initialized.
