### ISSUE TITLE
Add xcprivacy for UserDefaults usage

### ISSUE THREAD

**Issue by pxlRider** [kean/Pulse#248]
As per new Apple privacy reports, all apps and SDKs that are using any of those APIs need to declare type and reason in their privacy file. 
[https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api](url)
This package is using UserDefaults

**Comment by OneSman7** [comment]
It also uses File timestamp APIs (.creationDate and .modificationDate)
Please chack other API's at https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by samlapse** [comment]
Just opened this PR with the two required files, not 100% sure if anything else is required. 
https://github.com/kean/Pulse/pull/252

**Comment by kean** [comment]
Shipped in 4.10 thanks to @samlapse.
