### ISSUE TITLE
Feature Request: Custom network log descriptions

### ISSUE THREAD

**Issue by ejensen** [kean/Pulse#251]
The URL alone is insufficient to identify a network operation in certain scenarios. For example, in the GraphQL API, the URL for every request is identical. However, each GraphQL operation has a name within the request's body that identifies the operation. It would be useful to have the option to specify a custom description in `NetworkLogger.Request` so operations can be identified without needing to inspect each network entry. The description could default to [`URLSessionTask.taskDescription`](https://developer.apple.com/documentation/foundation/urlsessiontask/1409798-taskdescription)

**Comment by kean** [comment]
Great suggestion, @ejensen!

Implemented in https://github.com/kean/Pulse/pull/254 and shipped in [Pulse 4.2](https://github.com/kean/Pulse/releases/tag/4.2.0)
