### ISSUE TITLE
Crash when tapping "See all" when grouped by host

### ISSUE THREAD

**Issue by bjtitus** [kean/Pulse#263]
We noticed a crash when grouping by host in PulseUI's console:

> Thread 1: Fatal error: No ObservableObject of type ConsoleEnvironment found. A View.environmentObject(_:) for ConsoleEnvironment may be missing as an ancestor of this view.

### Steps to Reproduce

1. Open the PulseUI ConsoleView
2. Tap ⋯ > "Group By" > "Host"
3. Find a host with a "See All" cell and tap the "See All" cell
4. 💥 Crash

[CrashLog.ips.zip](https://github.com/user-attachments/files/15879646/podcasts-2024-06-17-203203.ips.zip)

Similar to https://github.com/kean/Pulse/issues/211, the issue seems to be with `ConsoleEnvironment` environment object not being set up.

**Comment by kean** [comment]
Hey, thanks for the report, @bjtitus.

Getting the SwiftUI environment work has been a challenge, as the behavior keeps changing across releases. It's fixed in [v4.2.5](https://github.com/kean/Pulse/releases/tag/4.2.5).
