### ISSUE TITLE
The project does not build on Xcode 13 beta 3 (13A5192j)

### ISSUE THREAD

**Issue by romanmazeev** [kean/Pulse#28]
The project does not build on Xcode 13 beta 3 (13A5192j) due to the fact that Apple has deprecated the `shared` property of `UIApplication` class.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/14664988/126737765-5a20599e-547b-4894-b1fb-e05ae6ea1dc1.png">

**Comment by vadimvitvickiy** [comment]
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/29

According to this thread this behaviour might be changed in the next betas
As an temporary workaround `@available(iOSApplicationExtension, unavailable)` annotations will let the lib to compile

**Comment by kean** [comment]
Thanks for the report. This change is unfortunate, especially if you are using SPM to modularize an app. Here is a [reply](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/32) from Apple that they will reconsider this behavior.

Pulse is not designed to be used in app extensions. If I start adding `@available(iOSApplicationExtension, unavailable)`, it will proliferate to the entire codebase. And there is no conditional compilation options available. So I suggest to skip Xcode 13 beta 3.
