### ISSUE TITLE
Fonts on macOS are too small

### ISSUE THREAD

**Issue by AvdLee** [kean/Pulse#282]
See this request from X:

![CleanShot 2024-07-08 at 08 25 16@2x](https://github.com/kean/Pulse/assets/4329185/f9ba8985-44da-4b62-86e6-c2dfc5178a01)

I think it makes sense to change `caption` to `body` for just the network requests. Potentially, we can make this optional by providing a `small` and `normal` size selection option in the header on the far right of the tabs.

**Comment by kean** [comment]
Thanks for the report; it was absolutely the case. I increased fonts in mulple places on macOS. I'll continue making small tweaks as I work on the new interations.
