### ISSUE TITLE
Stuck after purchase

### ISSUE THREAD

**Issue by ezefranca** [kean/Pulse#284]
1 - Download from App Store
2- Subscribe to the Anual Plan
3 - It will confirm.
4 - Get stuck (I  had to close / open the app)

There was no way to leave this screen (ESC). 

![Screenshot 2024-08-29 at 15 37 44](https://github.com/user-attachments/assets/3dd03102-6542-42a1-a50c-d790180e9996)

**Comment by kean** [comment]
Hey, I'll look into it right away, thanks!

**Comment by kean** [comment]
> 4 - Get stuck (I had to close / open the app)

I hope you were able to get access to the app after this?
I'm investigating, but I can't seem to be able to reproduce it with a StoreKit debug environment.

**Comment by kean** [comment]
I believe this is addressed in the latest version. 
I found a couple of other unrelated issues during testing, and these will also be addressed soon.
