### ISSUE TITLE
Support Moya?

### ISSUE THREAD

**Issue by bagusandinata** [kean/Pulse#30]
Hi, this is awesome. Does it support moya? I tried with _**Experimental.URLSessionProxy.shared.isEnabled**_, it doesn't detect moya request. Thank you

**Comment by kean** [comment]
`Experimental.URLSessionProxy.shared.isEnabled` - this should technically works with any URLSessionDataTask requests.

Adding a nicer non-experimental Moya integration would be nice. PRs are welcome.

**Comment by AgapovOne** [comment]
Pulse works fine for us with [Alamofire integraton](https://kean.blog/pulse/guides/networking#alamofire-integration). Moya is based on Alamofire.
