### ISSUE TITLE
Wrong version number in app download 0.16.0

### ISSUE THREAD

**Issue by suschizu** [kean/Pulse#33]
Just recognized that the 0.16.0 Pulse App download still contains version number 0.15.3 (instead of 0.16.0)

<img width="360" alt="Screen Shot 2021-08-22 at 22 13 07" src="https://user-images.githubusercontent.com/16004333/130368855-89246513-20ec-46b2-aaae-c95e11caac6e.png">

**Comment by kean** [comment]
No changes in the macOS app in this release, so I attached the previous build for convenience.

**Comment by suschizu** [comment]
Ok thanks for the information :)
