### ISSUE TITLE
v0.17.1 not compiling with Xcode 13 RC - Use of local variable 'buffer' before its declaration

### ISSUE THREAD

**Issue by TParizek** [kean/Pulse#40]
- Xcode 13.0 RC (13A233)
- Pulse 0.17.1

File: `LoggerStore.swift`
Line number: `565`
Error message: `Use of local variable 'buffer' before its declaration`

![LoggerStore_swift](https://user-images.githubusercontent.com/9418772/133431313-09e2cdd2-d6d1-45e6-9f68-dfbdc0bd0c0c.png)

Pulse 0.16.1 compiles without any error.

**Comment by kean** [comment]
Fix in [0.17.2](https://github.com/kean/Pulse/releases/tag/0.17.2)
