### ISSUE TITLE
Remote Loggging Question

### ISSUE THREAD

**Issue by ahmadmssm** [kean/Pulse#52]
First, thanks for this awesome too.
I followed the installation [guide](https://kean.blog/pulse/guides/pulse-pro) but I can't seem to find this step on the simulator with pulseFramwork installed on it
`Remote Logging on the device with the Pulse`
Am I missing something ?

**Comment by kean** [comment]
Hey, you should be able to find in the Settings tab. It's available on all platforms. Make sure you are using the latest version.

There are a couple of limitations:

- It's available on iOS 14+
- It only works with one store at a time. If you are using a custom store, make to sure to initialize the remote logger with it:

```swift
RemoteLogger.share.initialize(store: yourStore)
```

**Comment by ahmadmssm** [comment]
I might be doing something wrong but I can't find the settings tab

![Simulator Screen Shot - iPhone 11 - 2021-11-07 at 20 23 49](https://user-images.githubusercontent.com/26115953/140657145-84e61b56-7c1a-4c21-a33b-f64d88abc80c.png)

Also, I can upload a sample of my test project if you want.

Thank you...

**Comment by kean** [comment]
That looks like a screenshot from a Pulse iOS app (which I should probably just deprecate at this point). It's only purpose is to view log files (`.pulse` extension) stored on your device.

To use remote logging, you need to integrate `PulseUI` framework into your app. You can follow the steps from [guides](https://kean.blog/pulse/guides/logging).

And [here is](https://kean.blog/pulse/guides/pulse-pro#remote-logging) how it should look like.

Make sure to also add the following to your app's plist file:

Add the following keys to your .plist file:

```
<key>NSLocalNetworkUsageDescription</key>
<string>Network usage required for debugging purposes </string>
<key>NSBonjourServices</key>
<array>
  <string>_pulse._tcp</string>
</array>
```

**Comment by ahmadmssm** [comment]
Working now, Thanks.
