### ISSUE TITLE
WKWebView logging

### ISSUE THREAD

**Issue by vGubriienko** [kean/Pulse#59]
What steps need to do to log WKWebView network activity?

**Comment by kean** [comment]
There is no way to monitor WKWebView network requests using Pulse. I suggest using a network proxy or Safari Developer Tools.

**Comment by carltongibson** [comment]
@kean Can I ask, is this _feasible_ — I see you added the Enhancement label? Do you have any early breadcrumb thoughts on what would be needed? (I may have a rummage... 🤔)

**Comment by kean** [comment]
I'm going to close it because it doesn't seem to be feasible.
