### ISSUE TITLE
Gray area at the bottom of PulseUI MainView

### ISSUE THREAD

**Issue by av0c0der** [kean/Pulse#60]
Environment: iOS 15.0, iPhone 13 Pro Max and iOS 15.1, iPhone 11 Pro

<img src="https://user-images.githubusercontent.com/7991920/143925106-acbb0ef6-0de6-4507-934a-632bbfb19ab9.png" width="200"/>

If you open a particular request the area at the bottom enlarges.

<img src="https://user-images.githubusercontent.com/7991920/143925230-aaa98d6a-d105-4304-a807-d5760b11015d.png" width="200"/>

I'm not familiar with SwiftUI behaviour, it could be related to it. Here we can see UISplitViewController (using [lookin](http://lookin.work)).

<img src="https://user-images.githubusercontent.com/7991920/143925379-c80848af-0d83-4632-847f-f02d4f36d52a.png" width="500"/>

**Comment by TBXark** [comment]
try https://github.com/kean/Pulse/pull/73
