### ISSUE TITLE
Filter secrets from logs

### ISSUE THREAD

**Issue by jostster** [kean/Pulse#62]
A nice feature would be to provide a list of secrets that would be filtered for secure logging. For example auth tokens from headers or password parameters for signup / login calls. The ability to replace the secrets with `******` or `ab*****hi` would be great.

**Comment by kean** [comment]
You can use the [`willLogTask`](https://github.com/kean/Pulse/blob/792e84d58b9bf8e3b26cdb107bb076938cdc5539/Sources/PulseCore/NetworkLogger.swift#L17) closure in `NetworkLogger` to filter out the information you don't want to log.

**Comment by CavalcanteLeo** [comment]
have no idea how

**Comment by kean** [comment]
You can either modify the request `LoggedNetworkTask` by removing sensitive data or return `nil` to completely disable logging.

**Comment by CavalcanteLeo** [comment]
i want to modify the request and hide sensitive data from logging, but have no idea how to implement it
