### ISSUE TITLE
Metadata isn't shown along with source info

### ISSUE THREAD

**Issue by jostster** [kean/Pulse#64]
When using PulseUI to view logs on iOS it doesn't show metadata set via `logger[metadataKey: "foo"] = "bar"`. It also doesn't seem to be exported when exporting using a text file. The same information for `#file`,  `#function`, `#line` isn't shown either, but they are stored in the sqlite database.

**Comment by kean** [comment]
It's stored, but it's not surfaced in the UI yet. Ideally it should be and there should be respective filters. 

I have plans to add it at some point, but no immediate plans. PRs are welcome.

**Comment by michaelhenry** [comment]
@kean how about showing metadata as part of tags? #80

**Comment by kean** [comment]
Done in https://github.com/kean/Pulse/releases/tag/1.1.0.
