### ISSUE TITLE
Logo almost invisible when using GitHub in dark mode

### ISSUE THREAD

**Issue by peterfriese** [kean/Pulse#7]
The README looks great in light mode, but the logo and the download button are a bit difficult to read when using dark mode.

<img width="917" alt="Screenshot 2021-02-20 at 10 15 54" src="https://user-images.githubusercontent.com/232107/108590610-bc6b3b00-7364-11eb-9256-e6030996c34e.png">

Keep up the great work, this is really inspiring!

**Comment by kean** [comment]
Right, thanks for taking your time and open a defect. I had no idea because I disabled GitHub dark mode.

I added an outline, will see if there are better options. Unfortunately, GitHub doesn't support dark modes in README.
