### ISSUE TITLE
The presentation is reset to ConsoleMessageDetailsView after adding a new log

### ISSUE THREAD

**Issue by Konshin** [kean/Pulse#70]
When I investigate the details of a request (for example, the Response Body - `NetworkInspectorResponseView`) and a new log is added to the console (`ConsoleView`), the presentation returns to the details of the message (`ConsoleMessageDetailsView`)

**Steps to reproduce:**
1. Open the message details of the latest request from the console
2. Go to any child view from the message details (For example, Response Body)
3. Add a new log to the console (this happens when you have long requests or periodic requests)

**Expected behaviour:** 
The child view is visible (For example, Response Body)

**Actual behaviour:** 
The message details is visible

https://user-images.githubusercontent.com/10631753/159702130-2d6c4835-6a97-4c0e-a3eb-8d989dbc4d05.mov

**Comment by kean** [comment]
Thanks for the report. I'm able to reproduce it. It's a common issue with `List`, and I found some more related issues.

I'm going to address it in the upcoming release.

**Comment by kean** [comment]
Fixed in [1.0.0](https://github.com/kean/Pulse/releases/tag/1.0.0)
