### ISSUE TITLE
Logging to Xcode console

### ISSUE THREAD

**Issue by collinhundley** [kean/Pulse#71]
Is it possible to configure Pulse to output all logs to the Xcode console (like OSLog)?

**Comment by kean** [comment]
`Pulse.PersistentLogHandler` which is a logging backend for [SwiftLog](https://github.com/apple/swift-log). You can configure SwiftLog to have multiple logging backends, including OSLog (and there are [many others](https://github.com/apple/swift-log#selecting-a-logging-backend-implementation-applications-only))
