### ISSUE TITLE
Pulse is not being updated by Xcode

### ISSUE THREAD

**Issue by hugovanderlei** [kean/Pulse#75]
Hello, 

Xcode believes the next major version is 1.0.0 , so it is not updating to the newer versions of Pulse. 
Is there something in package configurations that could fix that?

![Captura de Tela 2022-04-28 às 10 53 36](https://user-images.githubusercontent.com/184836/165773934-507a5899-1017-45ba-a7d3-f223cb485fd5.png)

**Comment by kean** [comment]
Maybe it's cache. I just tested it it and it's automatically suggesting "1.0.0" for me.

<img width="829" alt="Screen Shot 2022-04-28 at 10 50 33 AM" src="https://user-images.githubusercontent.com/1567433/165780443-5b68ebf0-afd0-45f0-bbff-d52d0183bb9d.png">

**Comment by hugovanderlei** [comment]
Thanks, it was cache!
