### ISSUE TITLE
Question: What is the recommended way to use Pulse with macOS app?

### ISSUE THREAD

**Issue by vox-humana** [kean/Pulse#82]
It used to be possible to use `MainView` inside a Mac app but in this commit it was removed https://github.com/kean/Pulse/commit/c8a766a4a883f449ecd8511958381f9641618aa6#diff-9646ff2853fe810ca8e16dddcada3ac0beb65f41bc571bc330a0da7bd394c3cb
Probably, it is expected to use PulsePro to view logs, however, all UI for enabling remote logging is also not available for Mac target. I assume it is possible to reimplement all these views and viewmodels for macOS target but seems like I am missing something here.
What's the right way to set up realtime viewer (or Pulse in general) for a macOS app?

**Comment by kean** [comment]
I discontinued it to avoid maintaining two macOS codebases – it and [Pulse Pro](https://github.com/kean/PulsePro).

`Pulse.RemoteLogger` is publicly available and can be used for enabling remote logging. As of now, I suggest using it in a combination with Pulse Pro.

In general, I haven't put too much effort into supporting macOS apps yet. I see two potential directions:

1) Allow embedding Pulse Pro into macOS apps.
2) Making it easier to connect Pulse Pro to macOS apps. I'm thinking: providing a view for enabling remote logging on macOS; opening existing log file using Pulse Pro; maybe also basic SwiftUI-based log viewer like on watchOS.

**Comment by vox-humana** [comment]
Thank you for the answer. I'll try to enable remote logging in my app to use it with Pulse Pro app.

**Comment by cryptoAlgorithm** [comment]
@kean Hi, I love the direction this project is heading, but I'm also in the same situation of trying to integrate pulse into a macOS app.  How would I enable the RemoteLogger? the docs seem quite vague about it.

**Comment by kean** [comment]
@vox-humana , @cryptoAlgorithm I'm adding first-class macOS support in Pulse 2.0. You can see the latest changes here https://github.com/kean/Pulse/pull/89.

There is now going to be a simple Pulse view that you can integrate into your app to preview the logs (`PulseUI.MainView`). And the is a settings view (`PulseUI.SettingsVIew`) that you can use to enable remote logging.

**Comment by vox-humana** [comment]
That's great new. Thank you!
