### ISSUE TITLE
Logging messages from external package dependancy that uses swift-log

### ISSUE THREAD

**Issue by cryptoAlgorithm** [kean/Pulse#84]
My macOS app relies on an external package (also written by me), and even if I bootstrap swift-log in my AppDelegate like so: `		LoggingSystem.bootstrap(PersistentLogHandler.init)`, log messages from the package doesn't get captured by Pulse. Is there a recommended way to achieve this, or should I also bootstrap swift-log with Pulse in the package?

**Comment by kean** [comment]
Hi, are you referring to remote logging? If yes, this feature was previously disabled, but I'm adding it in Pulse 2.0. With this, you'll be able to easily connect your macOS app to Pulse Pro and view the logs there in real-time.

**Comment by cryptoAlgorithm** [comment]
@kean Nope, what I meant was that log messages from a package I depend on aren't being logged by Pulse, even though the package also uses SwiftLog.
